---
- name: Test
  hosts: localhost 
  gather_facts: false
  become: true
  tasks:
    - name: Comment out pipeline archive in fstab
      replace:
        dest: /home/vagrant/testfstab
        regexp: '(.*swap.*)'
        replace: '#\1'
 
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
