---
- hosts: localhost

  tasks:
    - name: Comment out pipeline archive in fstab
      lineinfile:
        dest: /etc/fstab
        regexp: '^//swap'
        line: '#//swap'
        state: present
      tags: update-fstab
